# Generated by Django 3.2.18 on 2023-04-24 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(default='微信用户', max_length=32)),
                ('openid', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('short', models.CharField(max_length=256)),
                ('lang', models.CharField(max_length=32)),
                ('neverDestory', models.BooleanField()),
                ('destoryTime', models.IntegerField()),
                ('postTime', models.IntegerField()),
                ('password', models.CharField(max_length=32)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codesharex.appuser')),
            ],
        ),
    ]
