# Generated by Django 3.2.18 on 2023-04-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesharex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='destoryTime',
            new_name='destory_time',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='neverDestory',
            new_name='never_destory',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='postTime',
            new_name='post_time',
        ),
        migrations.AlterField(
            model_name='content',
            name='password',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
