# Generated by Django 3.2.18 on 2023-05-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesharex', '0002_auto_20230424_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/avatar'),
        ),
    ]
