# Generated by Django 3.2.18 on 2023-05-14 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codesharex', '0003_appuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codesharex.appuser')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codesharex.content')),
            ],
        ),
    ]
