# Generated by Django 3.2.18 on 2023-05-14 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codesharex', '0004_collect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'App用户', 'verbose_name_plural': 'App用户'},
        ),
        migrations.AlterModelOptions(
            name='collect',
            options={'verbose_name': '收藏', 'verbose_name_plural': '收藏'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '页面', 'verbose_name_plural': '页面'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256)),
                ('time', models.IntegerField()),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codesharex.appuser')),
                ('belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codesharex.content')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
