# Generated by Django 3.2.18 on 2023-05-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesharex', '0007_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to',
            field=models.IntegerField(null=True),
        ),
    ]
