# Generated by Django 3.2.18 on 2023-05-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesharex', '0008_message_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to',
            field=models.IntegerField(null=True),
        ),
    ]
