# Generated by Django 3.2.18 on 2023-05-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesharex', '0009_comment_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=512),
        ),
    ]
