# Generated by Django 3.2.18 on 2023-05-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesharex', '0010_alter_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_openid',
            field=models.CharField(default='', max_length=64),
        ),
    ]
