# Generated by Django 3.2.18 on 2023-05-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesharex', '0011_auto_20230515_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default='微信用户', max_length=32),
        ),
    ]
