# Generated by Django 3.2.18 on 2023-05-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesharex', '0012_message_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_comment',
            field=models.IntegerField(null=True),
        ),
    ]
